### ISSUE TITLE
Feature: 

### ISSUE THREAD

**Issue by chrismast** [vjFaLk/firefly-bot#1]
Hi @vjFaLk ,
I am using your bot and it works well.
Just thought it might be good to enhance it in one place if possible as described [here on the Firefly III git](https://github.com/firefly-iii/firefly-iii/issues/3517).
Adding the account as indicator in an entry would enable putting expenses into the correct one.
Understand this will not work based on account name, but maybe some account ID?

**Comment by vjFaLk** [comment]
Hey @chrismast , sorry for taking so long to reply to this, but I just pushed a new update with a bunch of new features and fixes (that includes the feature you requested :). Please check out the [Changelog](https://github.com/vjFaLk/firefly-bot/releases/tag/v0.0.2). If you're still using the bot / are interested in using it again, do try it out and let me know.

**Comment by chrismast** [comment]
Thanks @vjFaLk ! That is awesome. I am indeed using your bot as the Android Apps are still lacking user experience (in my point of view). Will spin up the new bot later today and give you some feedback.
I can see that the accounts are by name which can be complex depending on the account name length, but doable. Is there any way to assign an account ID and use a number instead? (i.e. Cash = 1, Credit Card #1 = 2 etc.)

**Comment by chrismast** [comment]
@vjFaLk : Just updated the bot and it works as expected. Thanks!
I also created a docker-compose.yml in case you want to put it in the how-to:

```
version: '3.3'
services:
    firefly-telegram-bot:
        container_name: firefly-bot
        image: vjfalk1/firefly-telegram-bot
        environment:
            - TELEGRAM_BOT_TOKEN=FIREFLY-TOKEN
        volumes:
            - /local/folder/:/config
        restart: unless-stopped
```

One further enhancement idea instead of using an ID for the account would be to i.e. enter a spend (5, Starbucks, Food) on which the bot then would ask to which source account it show go (I guess source accounts would be a lot more limited then destination accounts?).
Anyway, thanks for this current enhancement already, works good so far.
